### ISSUE TITLE
遇到一个内存相关的报错

### ISSUE THREAD

**Issue by DavideSOGG** [ricky97135/eramaouEX#1]
![9ACB66EA-608D-4797-B81B-A20BB46389AF](https://user-images.githubusercontent.com/28831997/208945554-715df2d1-7d52-455c-91b3-c42c84c7b3c7.png)
![B38241FC-C51B-49C1-B6CF-A464AD2DF486](https://user-images.githubusercontent.com/28831997/208945583-5d86aa90-c2fc-4216-abfb-91f4d23b1812.png)

触发BUG时的几个主要事件
❶地下城内派出勇者处于迎击的状态下 
❷禁止怪物迎击 现在：OFF
❸侵攻时怪物数量满足最低600只的要求 选择派遣一半去进攻

**Comment by DavideSOGG** [comment]
版本是今年9月23日的最新版

**Comment by ricky97135** [comment]
電腦RAM多少

**Comment by ricky97135** [comment]
檢查了一下 看起來不像是程式的錯誤

**Comment by DavideSOGG** [comment]
> 電腦RAM多少

WindowsXP SP3 1G内存

看报错像是内存溢出？

**Comment by ricky97135** [comment]
你加到到

**Comment by ricky97135** [comment]
你加到4G試試看吧

**Comment by ricky97135** [comment]
程式是鐵定沒法優化的

**Comment by DavideSOGG** [comment]
> 程式是鐵定沒法優化的

嗯，应该是启动器那边的问题，我找个新版本试试
